Periods:
  "1 Top": ["1T", "1Top", "1 Top"]
  "1 Bottom": ["1B", "1 Bot","1Bottom"]
Placements:
  "Batter's Eye": ["BE", "Batter"]
  "Mound": ["M", "PM","Pitcher"]
  "Center Left Bottom [P2]": ["CLB"]
  "Center Right Top [P2]": ["CRT"]
  "Left Top [P1]": ["LT"]
  "Right Bottom [P1]": ["RB"]
